title: Customised GPT for DfAM
description: Supplementary material for "A concept for AI supported knowledge extraction in design for additive manufacturing" (Design Conference 2026)
theme: jekyll-theme-cayman
